Issue 49: Update ingestor to add dummy email if dataset has bad email
als-computing/splash_flows_globus pull request #50
Opened 2024-12-23 19:34 UTC by davramov

Addressing this issue: https://github.com/als-computing/splash_flows_globus/issues/49

Fixed a couple of typos, linting errors, and most importantly replaced `unknown` with `unknown@example.com` for the `contactEmail` field in the `ingest_tomo832` module.

Testing this locally before merging.

2025-03-27 16:34 UTC, dylanmcreynolds requested changes

2025-04-04 21:49 UTC, davramov commented on orchestration/flows/bl832/ingest_tomo832.py
> +      - The input is not a string,
I created a few new pytests in `orchestration/_tests/test_scicat.py` for testing `clean_email()`

2025-04-04 21:49 UTC, davramov commented on orchestration/flows/bl832/ingest_tomo832.py
> +def test_ingest_raw_tomo() -> bool:
I created a new pytest in `orchestration/_tests/test_scicat.py`

2025-04-04 21:49 UTC, davramov commented on orchestration/flows/scicat/ingest.py
> +    dotenv.load_dotenv()
I deleted this from the script.

2025-04-04 21:49 UTC, davramov commented on orchestration/flows/scicat/ingest.py
> +    try:
I left a comment for this in the code.

2025-04-19 00:22 UTC, davramov commented
@dylanmcreynolds Can we merge this?

2025-04-22 17:16 UTC, merged